name: yandex_mapkit_demo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  yandex_mapkit: ^3.3.3
  equatable: ^2.0.5
  permission_handler: ^11.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  go_router: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
